import LayoutDefault from '@/layouts/layout-default';
import NextImage from '@/components/base/next-image';
import Link from 'next/link';

export default function Home() {
  return (
    <LayoutDefault title={'About Next App'} description={'Generated by create next app'}>
      <h1>About Page</h1>
      <NextImage src={"vercel.svg"} alt={"Vercel Logo"} />
      <br />
      <Link href="/">to Home page</Link>
    </LayoutDefault>
  );
}
