import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta
          name="description"
          content="About page. Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/vvebdev-nextjs/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>About page</h1>
      </main>
    </>
  );
}
