import LayoutEmpty from '@/layouts/layout-empty';
import NextImage from '@/components/base/next-image';
import Link from 'next/link';

export default function AboutPage() {
  return (
    <LayoutEmpty title={'About Next App'} description={'Generated by create next app'}>
      <h1>About Page</h1>
      <Link href="/">to Home page</Link>
      <br />
      <br />
      <NextImage src={"vercel.svg"} alt={"Vercel Logo"} />
    </LayoutEmpty>
  );
}
