import LayoutEmpty from '@/layouts/layout-empty';
import CreateProject from '@/components/create-project';
import NextImage from '@/components/base/next-image';
import Link from 'next/link';

export default function CreateProjectPage() {
  return (
    <LayoutEmpty title={'Create Project Page'} description={'Generated by create next app'}>
      <Link href="/">to Home page</Link>
      <br />
      <br />
      <CreateProject />
    </LayoutEmpty>
  );
}
