import NextImage from '@/components/base/next-image';
import LayoutDefault from '@/layouts/layout-default';
import Link from 'next/link'

export default function Home() {
  return (
    <LayoutDefault title={'Homepage'} description={'Generated by create next app'}>
      <h1>Homepage</h1>
      <NextImage src={"vercel.svg"} alt={"Vercel Logo"} />
      <br />
      <Link href="/about">to About page</Link>
    </LayoutDefault>
  );
}
